# Generated by Django 4.2.1 on 2023-07-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('enrolled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='crud_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('cat1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_exam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='crud_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('cat2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('cat3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('exam_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('grade', models.CharField(default=None, max_length=1, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='crud_app.unit')),
            ],
        ),
    ]
