# Generated by Django 4.2.1 on 2023-08-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_title_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.course'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.course'),
        ),
    ]
