# Generated by Django 4.2.1 on 2023-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_alter_student_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
