# Generated by Django 4.2.1 on 2023-08-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_alter_unit_unit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='graded',
        ),
        migrations.AddField(
            model_name='student',
            name='graded',
            field=models.BooleanField(default=True),
        ),
    ]
