# Generated by Django 4.2.1 on 2023-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0008_remove_studentmarks_graded_student_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
