# Generated by Django 4.2.1 on 2023-08-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0010_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unit_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.unit'),
        ),
    ]
